version: "3.1"
services:
  mysql:
    container_name: registerform
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registerform
      MYSQL_PASSWORD: root
